次のデータに対して、Kyotoの列だけ抜き出してみましょう。

In [1]:
import pandas as pd
import numpy as np

In [2]:
hier_df1 = pd.DataFrame(
    np.arange(12).reshape((3,4)),
    index = [['c','d','d'],[1,2,1]],
    columns = [
        ['Kyoto','Nagoya','Hokkaido','Kyoto'],
        ['Yellow','Yellow','Red','Blue']
    ]
    )
hier_df1.index.names = ['key1','key2']
hier_df1.columns.names = ['city','color']
hier_df1

city       Kyoto Nagoya Hokkaido Kyoto
color     Yellow Yellow      Red  Blue
key1 key2
c    1         0      1        2     3
d    2         4      5        6     7
     1         8      9       10    11

In [3]:
hier_df1.groupby('key2').mean()

city   Kyoto Nagoya Hokkaido Kyoto
color Yellow Yellow      Red  Blue
key2
1        4.0    5.0      6.0   7.0
2        4.0    5.0      6.0   7.0