総合問題 7-1 時系列データ分析】
ここでは、本章で身に付けたPandasやScipyなどを使って、時系列データついて扱っていきましょう。
1.データの取得と確認 … 下記のサイトより、dow_jones_index.zipをダウンロードし、含まれているdow_jones_
index.dataを使って、データを読み込み、はじめの5 行を表示してください。またデータのそれぞれのカラム情
報等を見て、NaNなどがあるか確認してください。
https://archive.ics.uci.edu/ml/machine-learning-databases/00312/dow_jones_index.zip
2.データの加工 … カラムのopen、high、low、close等のデータは数字の前に$マークが付いているため、これを
取り除いてください。また、日時をdate型で読み込んでいない場合は、date型に変換しましょう。
3.カラムのcloseについて、各stockごとの要約統計量を算出してください。
4.カラムのcloseについて、各stockの相関を算出する相関行列を出してください。また、Seabornのheatmap関
数を使って、相関行列のヒートマップを描いてみましょう（ヒント：Pandasのcorrメソッドを使います）。
5.4で算出した相関行列の中で一番相関係数が高いstockの組み合わせを抽出してください。さらに、その中でもっ
とも相関係数が高いペアを抜き出し、それぞれの時系列グラフを描いてください。
6.Pandasのrollingメソッド（窓関数）を使って、上記で使った各stockごとに、closeの過去 5 期（5 週間）移動
平均時系列データを計算してください。
7.Pandasのshiftメソッドを使って、上記で使ったstockごとに、closeの前期（1 週前）との比の対数時系列デー
タを計算してください。さらに、この中で、一番ボラティリティ（標準偏差）が一番大きいstockと小さいstockを
抜き出し、その対数変化率グラフを書いてください。
※6、7について、196ページのコラムで補足しています。こちらもご覧ください。

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('../Chap03/student-mat.csv',sep=';')
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [5]:
data.groupby(['age', 'sex'])['G1'].mean().unstack()

sex          F          M
age
15   10.052632  12.250000
16   10.203704  11.740000
17   11.103448  10.600000
18   10.883721  10.538462
19   10.642857   9.700000
20   15.000000  13.000000
21         NaN  10.000000
22         NaN   6.000000